baseURL = "https://hl2.github.io/hl2.dev"
languageCode = "en-gb"
title = "hl2 Developers"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableRobotsTXT = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Build amazing IoT projects with hl2 technologies"
  images = ["images/open-graph-cover.png"]
  hl2WebsiteURL = "https://hl2.com"
  twitterProfileURL = "https://twitter.com/hl2_fr"
  linkedInProfileURL = "https://www.linkedin.com/company/hl2-fr"
  gitHubProfileURL = "https://github.com/hl2"
  gitHubRepositoryURL = "https://github.com/hl2/hl2.dev"
  googleTagManagerID = "GTM-5WGKRMB"
  hl2PanoramaOpenAPIRepositoryURL = "https://github.com/hl2/hl2-panorama-openapi"
  contactEmail = "contact@hl2.com"
  supportEmail = "support@hl2.com"
